version: '3.9'
services:
  app:
    container_name: dockertest
    image: dockertest
    build: ./
    ports:
      - "8888:8888"
    depends_on:
      - postgresql
  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=admin
      - POSTGRES_DB=database